from __future__ import annotations

import io
import re
from typing import Any

from docx import Document
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt
TYPE_LABELS = {
    "lesson": "Lesson Plan",
    "activity": "Activity",
    "worksheet": "Worksheet",
    "assessment": "Assessment",
}

_HEADING_BREAK_WORDS = ("ANSWER KEY", "TEACHER NOTES", "MARKING GUIDE")
_MARKDOWN_PREFIX = re.compile(r"^\s{0,3}(#{1,6})\s+(.*)$")
_NUMBERED_ITEM = re.compile(r"^\s*(\d+)[.)]\s+(.*)$")
_BULLET_ITEM = re.compile(r"^\s*[-*•]\s+(.*)$")


def _clean_inline_markdown(text: str) -> str:
    cleaned = text.replace("**", "")
    cleaned = cleaned.replace("`", "")
    return cleaned.strip()


def _safe_filename(value: object, *, material_id: int) -> str:
    title = _clean_inline_markdown(str(value or "TeacherOS Material"))
    title = re.sub(r'[<>:"/\\|?*\x00-\x1F]', "", title)
    title = re.sub(r"\s+", " ", title).strip(" .")
    if not title:
        title = "TeacherOS Material"
    if len(title) > 70:
        title = title[:70].rstrip()
    return f"{title} - #{material_id}.docx"


def _set_cell_shading(cell: Any, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shading = tc_pr.find(qn("w:shd"))
    if shading is None:
        shading = OxmlElement("w:shd")
        tc_pr.append(shading)
    shading.set(qn("w:fill"), fill)


def _set_repeat_table_header(row: Any) -> None:
    tr_pr = row._tr.get_or_add_trPr()
    tbl_header = OxmlElement("w:tblHeader")
    tbl_header.set(qn("w:val"), "true")
    tr_pr.append(tbl_header)


def _configure_document(document: Document, material: dict[str, Any]) -> None:
    section = document.sections[0]
    section.page_width = Inches(8.27)
    section.page_height = Inches(11.69)
    section.top_margin = Inches(0.65)
    section.bottom_margin = Inches(0.65)
    section.left_margin = Inches(0.7)
    section.right_margin = Inches(0.7)
    section.header_distance = Inches(0.3)
    section.footer_distance = Inches(0.3)

    normal = document.styles["Normal"]
    normal.font.name = "Arial"
    normal.font.size = Pt(10.5)
    normal.paragraph_format.space_after = Pt(4)
    normal.paragraph_format.line_spacing = 1.08

    title_style = document.styles["Title"]
    title_style.font.name = "Arial"
    title_style.font.size = Pt(20)
    title_style.font.bold = True
    title_style.paragraph_format.space_after = Pt(8)

    for style_name, size in (("Heading 1", 14), ("Heading 2", 12), ("Heading 3", 11)):
        style = document.styles[style_name]
        style.font.name = "Arial"
        style.font.size = Pt(size)
        style.font.bold = True
        style.paragraph_format.space_before = Pt(8)
        style.paragraph_format.space_after = Pt(4)
        style.paragraph_format.keep_with_next = True

    header = section.header.paragraphs[0]
    header.text = "TeacherOS  •  Classroom Material"
    header.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    for run in header.runs:
        run.font.name = "Arial"
        run.font.size = Pt(8)
        run.font.bold = True

    footer = section.footer.paragraphs[0]
    footer.text = f"Generated by TeacherOS  |  Library ID #{material.get('id', '')}"
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in footer.runs:
        run.font.name = "Arial"
        run.font.size = Pt(8)


def _add_metadata_table(document: Document, material: dict[str, Any]) -> None:
    type_label = TYPE_LABELS.get(str(material.get("material_type") or ""), "Material")
    subtype = str(material.get("subtype") or "").strip()
    level = str(material.get("level") or "").strip()
    topic = str(material.get("topic") or "").strip()
    created_at = str(material.get("created_at") or "").strip()

    rows: list[tuple[str, str]] = [("Type", type_label)]
    if subtype and subtype.lower() != type_label.lower():
        rows.append(("Subtype", subtype))
    if level:
        rows.append(("CEFR level", level))
    if topic:
        rows.append(("Topic", topic))
    if created_at:
        rows.append(("Saved", f"{created_at[:16]} UTC"))

    metadata = material.get("metadata")
    if isinstance(metadata, dict):
        grammar = str(metadata.get("grammar") or "").strip()
        duration = metadata.get("duration_minutes")
        question_format = str(metadata.get("question_format") or "").strip()
        question_count = metadata.get("question_count")
        if grammar:
            rows.append(("Grammar", grammar))
        if isinstance(duration, int):
            rows.append(("Duration", f"{duration} minutes"))
        if question_format:
            rows.append(("Question format", question_format))
        if isinstance(question_count, int):
            rows.append(("Questions", str(question_count)))

    table = document.add_table(rows=len(rows), cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = True
    table.style = "Table Grid"
    _set_repeat_table_header(table.rows[0])

    for row_index, (label, value) in enumerate(rows):
        label_cell, value_cell = table.rows[row_index].cells
        label_cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        value_cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER
        label_cell.text = label
        value_cell.text = value
        _set_cell_shading(label_cell, "E7E6E6")
        for run in label_cell.paragraphs[0].runs:
            run.bold = True
            run.font.name = "Arial"
            run.font.size = Pt(9)
        for run in value_cell.paragraphs[0].runs:
            run.font.name = "Arial"
            run.font.size = Pt(9)

    document.add_paragraph()


def _looks_like_heading(text: str) -> bool:
    if not text or len(text) > 95:
        return False
    letters = [character for character in text if character.isalpha()]
    if not letters:
        return False
    uppercase_ratio = sum(character.isupper() for character in letters) / len(letters)
    return uppercase_ratio >= 0.8 and not text.endswith((".", "?", "!"))


def _add_content(document: Document, content: str) -> None:
    page_break_added = False

    for raw_line in content.replace("\r\n", "\n").replace("\r", "\n").split("\n"):
        line = raw_line.strip()
        if not line:
            continue

        markdown_heading = _MARKDOWN_PREFIX.match(line)
        if markdown_heading:
            marker, heading_text = markdown_heading.groups()
            heading = _clean_inline_markdown(heading_text)
            heading_level = 1 if len(marker) <= 2 else 2
            if not page_break_added and any(word in heading.upper() for word in _HEADING_BREAK_WORDS):
                document.add_page_break()
                page_break_added = True
            document.add_heading(heading, level=heading_level)
            continue

        cleaned = _clean_inline_markdown(line)
        if _looks_like_heading(cleaned):
            if not page_break_added and any(word in cleaned.upper() for word in _HEADING_BREAK_WORDS):
                document.add_page_break()
                page_break_added = True
            document.add_heading(cleaned.title() if cleaned.isupper() else cleaned, level=1)
            continue

        numbered = _NUMBERED_ITEM.match(cleaned)
        if numbered:
            number, item_text = numbered.groups()
            paragraph = document.add_paragraph()
            paragraph.paragraph_format.left_indent = Inches(0.24)
            paragraph.paragraph_format.first_line_indent = Inches(-0.24)
            paragraph.add_run(f"{number}.  {_clean_inline_markdown(item_text)}")
            continue

        bullet = _BULLET_ITEM.match(cleaned)
        if bullet:
            paragraph = document.add_paragraph(style="List Bullet")
            paragraph.add_run(_clean_inline_markdown(bullet.group(1)))
            continue

        paragraph = document.add_paragraph(cleaned)
        paragraph.paragraph_format.keep_together = False


def build_word_document(material: dict[str, Any]) -> Document:
    """Build a polished classroom-ready Word document from one saved material."""
    document = Document()
    _configure_document(document, material)

    title = _clean_inline_markdown(str(material.get("title") or "TeacherOS Material"))
    title_paragraph = document.add_paragraph(style="Title")
    title_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_paragraph.add_run(title)

    subtitle = TYPE_LABELS.get(str(material.get("material_type") or ""), "Classroom Material")
    subtitle_paragraph = document.add_paragraph()
    subtitle_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle_paragraph.add_run(subtitle)
    subtitle_run.bold = True
    subtitle_run.font.name = "Arial"
    subtitle_run.font.size = Pt(10)

    _add_metadata_table(document, material)

    content = str(material.get("content") or "").strip()
    if content:
        _add_content(document, content)
    else:
        document.add_paragraph("This saved material has no readable content.")

    return document


def create_word_export(material: dict[str, Any]) -> tuple[io.BytesIO, str]:
    """Return an in-memory DOCX stream and a safe download filename."""
    material_id = int(material.get("id") or 0)
    document = build_word_document(material)
    output = io.BytesIO()
    document.save(output)
    output.seek(0)
    filename = _safe_filename(material.get("title"), material_id=material_id)
    return output, filename
